other lab works/app/todo/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import PasswordField, BooleanField, SelectField
from wtforms import StringField, EmailField, SubmitField
from wtforms import TextAreaField
from wtforms.validators import DataRequired, Email, Length, ValidationError
from wtforms.validators import EqualTo, Regexp

from app.models import User


class TodoForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description')
    status = SelectField('Status', choices=[(0, 'Todo'), (1, 'In Progress'), (2, 'Done')], coerce=int, default=0)

other lab works/app/todo/__init__.py
from flask import Blueprint

todo_bp = Blueprint("todo", __name__, template_folder="templates")

from . import views

other lab works/app/todo/views.py
import os
from datetime import datetime

from flask import current_app as app
from flask import flash
from flask import render_template, request, redirect, url_for

from app import db
from app.models import Todo
from app.todo import todo_bp
from app.todo.forms import TodoForm


def get_data():
    operating_system = os.uname()
    user_agent = request.headers.get('User-Agent')
    time_now = datetime.now()
    return {
        "operating_system": operating_system,
        "user_agent": user_agent,
        "time_now": time_now,
    }



@todo_bp.route('/todo', methods=['GET', 'POST'])
def todo():
    form = TodoForm()

    if form.validate_on_submit():
        new_todo = Todo(title=form.title.data, description=form.description.data)
        db.session.add(new_todo)
        db.session.commit()
        flash('Todo added successfully!', 'success')
        return redirect(url_for('todo.todo'))

    todos = Todo.query.all()
    return render_template('todo.html', data=get_data(), form=form, todos=todos)


@todo_bp.route('/todo/<int:todo_id>', methods=['GET', 'POST'])
def edit_todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    form = TodoForm(obj=todo)

    if form.validate_on_submit():
        todo.title = form.title.data
        todo.description = form.description.data
        todo.status = form.status.data
        db.session.commit()
        flash('Todo updated successfully!', 'success')
        return redirect(url_for('todo.todo'))

    return render_template('edit_todo.html', data=get_data(), form=form, todo=todo)


@todo_bp.route('/todo/delete/<int:todo_id>', methods=['POST'])
def delete_todo(todo_id):
    todo = Todo.query.get_or_404(todo_id)
    db.session.delete(todo)
    db.session.commit()
    flash('Todo deleted successfully!', 'success')
    return redirect(url_for('todo.todo'))

other lab works/app/todo/templates/edit_todo.html
{% extends 'base.html' %}

{% block content %}
    <h2>Edit Todo</h2>
    <form method="post" action="{{ url_for('todo.edit_todo', todo_id=todo.id) }}">
        {{ form.hidden_tag() }}
        {{ form.title.label }} {{ form.title }}
        {{ form.description.label }} {{ form.description }}
        {{ form.status.label }} {{ form.status }}
        <button type="submit">Update Todo</button>
    </form>
{% endblock %}

other lab works/app/todo/templates/todo.html
{% extends 'base.html' %}
{% from 'render_field.html' import get_status_label %}

{% block content %}
    <h2>Todo List</h2>
    <ul>
        {% for todo in todos %}
            <li>{{ todo.title }} - {{ todo.description }} -> Status: {{ get_status_label(todo.status) }}
                <a href="{{ url_for('todo.edit_todo', todo_id=todo.id) }}">Edit</a>
                <form method="post" action="{{ url_for('todo.delete_todo', todo_id=todo.id) }}" style="display:inline;">
                    <button type="submit" onclick="return confirm('Are you sure?')">Delete</button>
                </form>
            </li>
        {% endfor %}
    </ul>

    <h2>Add Todo</h2>
    <form method="post" action="{{ url_for('todo.todo') }}">
        {{ form.hidden_tag() }}
        {{ form.title.label }} {{ form.title }}
        {{ form.description.label }} {{ form.description }}
        <button type="submit">Add Todo</button>
    </form>
{% endblock %}