other lab works/app/cookie/__init__.py
from flask import Blueprint

cookie_bp = Blueprint("cookie", __name__, template_folder="templates")

from . import views

other lab works/app/cookie/views.py
from datetime import datetime
import os

from flask import request, render_template, session, make_response, redirect, url_for
from flask_login import login_required

from app.cookie import cookie_bp


def get_data():
    operating_system = os.uname()
    user_agent = request.headers.get('User-Agent')
    time_now = datetime.now()
    return {
        "operating_system": operating_system,
        "user_agent": user_agent,
        "time_now": time_now,
    }


@cookie_bp.route('/info', methods=['GET'])
@login_required
def info():
    cookies = request.cookies
    return render_template('info.html', data=get_data(), cookies=cookies)


@cookie_bp.route('/add_cookie', methods=["GET", "POST"])
@login_required
def add_cookie():
    if 'username' in session:
        key = request.form['key']
        value = request.form['value']

        response = make_response(redirect(url_for('cookie.info')))
        response.set_cookie(key, value)
        return response
    else:
        return redirect(url_for('authet.login'))


@cookie_bp.route('/delete_all_cookies', methods=['GET'])
@login_required
def delete_all_cookies():
    if 'username' in session:
        response = make_response(redirect(url_for('cookie.info')))
        for key in request.cookies.keys():
            response.delete_cookie(key)
        return response
    else:
        return redirect(url_for('authet.login'))

other lab works/app/cookie/templates/info.html
{% extends 'base.html' %}

{% block title %}Info{% endblock %}

{% block content %}
    <h1>Дані користувача</h1>
    <p>Привіт, {{ current_user.username }}!</p>
    <p>Операційна система: {{ data.operating_system }}</p>
    <p>User-Agent: {{ data.user_agent }}</p>
    <p>Час зараз: {{ data.time_now }}</p>
    <a href="{{ url_for('authet.logout') }}">Вийти</a>

    <h2>Інформація про кукі:</h2>
    <table>
        <tr>
            <th>Ключ</th>
            <th>Значення</th>
            <th>Термін дії</th>
        </tr>
        {% for key, value in cookies.items() %}
            <tr>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
                <td>{{ request.cookies.get(key).max_age }} сек</td>
            </tr>
        {% endfor %}
    </table>
    <hr>
    <form action="{{ url_for('cookie.add_cookie') }}" method="POST">
        <label for="key">Ключ:</label>
        <input type="text" id="key" name="key" required>
        <br>
        <label for="value">Значення:</label>
        <input type="text" id="value" name="value" required>
        <br>
        <input type="submit" value="Додати кукі">
    </form>
    <hr>
    <a href="{{ url_for('cookie.delete_all_cookies') }}">Видалити всі кукі</a>
{% endblock %}