other lab works/app/user/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import EmailField, StringField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length, Email

from app.models import User


class UpdateAccountForm(FlaskForm):
    new_username = StringField('Change username', validators=[DataRequired(), Length(min=4, max=25)])
    new_email = EmailField('Change email', validators=[DataRequired(), Email()])
    profile_picture = FileField('Update Profile Picture',
                                validators=[
        FileAllowed(['jpg', 'png', 'jpeg'], 'Images only! Please upload a valid image.')
    ])
    about_me = TextAreaField('About me')

    def validate_new_email(self, field):
        user = User.query.filter(User.email == field.data).first()
        if user and user.id != current_user.id:
            raise ValidationError("Email is already in use by another user.")

    def validate_new_username(self, field):
        user = User.query.filter(User.username == field.data).first()
        if user and user.id != current_user.id:
            raise ValidationError("Username is already in use by another user.")

other lab works/app/user/__init__.py
from flask import Blueprint

user_bp = Blueprint("user", __name__, template_folder="templates")

from . import views

other lab works/app/user/views.py
import os
from datetime import datetime

from flask import request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from app import db
from app.auth.forms import ChangePassword
from app.models import User
from app.user import user_bp
from app.user.forms import UpdateAccountForm


def get_data():
    operating_system = os.uname()
    user_agent = request.headers.get('User-Agent')
    time_now = datetime.now()
    return {
        "operating_system": operating_system,
        "user_agent": user_agent,
        "time_now": time_now,
    }


@user_bp.route("/users")
@login_required
def users():
    all_users = User.query.all()
    return render_template('users.html', all_users=all_users, data=get_data())


@user_bp.route("/account")
@login_required
def account():
    form = ChangePassword()
    update_form = UpdateAccountForm()
    update_form.new_email.data = current_user.email
    update_form.new_username.data = current_user.username
    update_form.about_me.data = current_user.about_me
    return render_template('account.html', title='Account', data=get_data(), form=form, update_form=update_form)


@user_bp.route('/change_login', methods=['POST'])
@login_required
def change_login():
    form = UpdateAccountForm()
    if not form.validate_on_submit():
        # if not current_user.verify_password(form.old_password.data):
        #     flash("Old password is incorect", "danger")
        return render_template('account.html', title='Account', data=get_data(), form=ChangePassword(),
                               update_form=form)
        # return redirect(url_for('account'))
    current_user.username = form.new_username.data
    current_user.email = form.new_email.data
    current_user.about_me = form.about_me.data
    profile_photo = form.profile_picture.data
    if profile_photo:
        filename = secure_filename(profile_photo.filename)
        filepath = os.path.join('app/static/images/', filename)
        profile_photo.save(filepath)
        current_user.image_file = filename

    db.session.commit()
    flash("Your data was changed!", "success")
    return redirect(url_for('user.account'))


@user_bp.after_request
def update_user_last_seen(resp):
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.commit()

    return resp

other lab works/app/user/templates/account.html
{% extends 'base.html' %}
{% from 'render_field.html' import render_field %}

{% block title %}Account{% endblock %}

{% block content %}
    <h1>Дані користувача</h1>
    <img class="user_images" src="{{ url_for('static', filename='images/' + current_user.image_file) }}"
         alt="User Photo">
    <p>{{ current_user.username }}</p>
    <p>{{ current_user.email }}</p>
    <p>Last seen: {{ current_user.last_seen }}</p>
    <p>About me: {{ current_user.about_me }}</p>
    <p>Час зараз: {{ data.time_now }}</p>
    <a href="{{ url_for('authet.logout') }}">Вийти</a>

    <form action="{{ url_for('authet.change_password') }}" method="POST">
        {{ form.csrf_token }}

        {{ render_field(form.old_password) }}
        {{ render_field(form.new_password) }}
        {{ render_field(form.confirm_password) }}
        <input type="submit" value="Змінити пароль">
    </form>
    <form action="{{ url_for('user.change_login') }}" method="POST" enctype="multipart/form-data">
        {{ update_form.csrf_token }}

        {{ render_field(update_form.new_username) }}
        {{ render_field(update_form.new_email) }}
        {{ render_field(update_form.about_me) }}
        {{ render_field(update_form.profile_picture) }}
        <input type="submit" value="Підтвердити зміни">
    </form>
{% endblock %}

other lab works/app/user/templates/users.html
{% extends 'base.html' %}
{% from 'render_field.html' import render_field %}

{% block title %}Users{% endblock %}

{% block content %}
    <table>
        <thead>
        <tr>
            <th scope="col">email</th>
            <th scope="col">username</th>
            <th scope="col">last seen</th>
        </tr>
        </thead>
        <tbody>
        {% for user in all_users %}
            <tr>
                <td>{{ user.email }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.last_seen }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}